@echo off
echo Starting Backend...
start /min cmd /k "cd backend && node --watch server.js"

echo Starting Frontend...
start /min cmd /k "cd frontend && npm run dev"

echo Waiting for Frontend to start...
timeout /t 5 >nul

echo Opening Browser...
start http://localhost:5173/